"""add soft delete support

Revision ID: 1ca0dbde9760
Revises: 3a5e0b277882
Create Date: 2026-06-08 00:07:21.464450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca0dbde9760'
down_revision: Union[str, Sequence[str], None] = '3a5e0b277882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'contracts',
        sa.Column(
            'is_deleted',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')
        )
    )

    op.add_column(
        'users',
        sa.Column(
            'is_deleted',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')
        )
    )

    # Optional: remove DB default afterwards
    op.alter_column('contracts', 'is_deleted', server_default=None)
    op.alter_column('users', 'is_deleted', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('contracts', 'is_deleted')
    # ### end Alembic commands ###
