"""add file and AI columns to contracts

Revision ID: 3a5e0b277882
Revises: b964d789c90d
Create Date: 2026-06-05 15:02:56.786791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5e0b277882'
down_revision: Union[str, Sequence[str], None] = 'b964d789c90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('contracts', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('contracts', sa.Column('supplier', sa.String(length=255), nullable=True))
    op.add_column('contracts', sa.Column('value', sa.String(length=100), nullable=True))
    op.add_column('contracts', sa.Column('notice_period', sa.String(length=100), nullable=True))
    op.add_column('contracts', sa.Column('ai_summary', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('risk_flag', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('key_clauses', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'key_clauses')
    op.drop_column('contracts', 'risk_flag')
    op.drop_column('contracts', 'ai_summary')
    op.drop_column('contracts', 'notice_period')
    op.drop_column('contracts', 'value')
    op.drop_column('contracts', 'supplier')
    op.drop_column('contracts', 'start_date')
    op.drop_column('contracts', 'file_path')
    # ### end Alembic commands ###
